services:
  postgres-db:
    container_name: e_commerce-db
    image: postgres:15.4-alpine3.18
    restart: always
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=e_commerce
    volumes: 
      - postgres-db-data:/var/lib/postgresql/data
      - ./schemes/:/docker-entrypoint-initdb.d/
      
volumes:
  postgres-db-data: